// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldOfWarcraft.Database.Context;

#nullable disable

namespace WorldOfWarcraft.Database.Migrations
{
    [DbContext(typeof(WorldOfWarcraftDbContext))]
    partial class WorldOfWarcraftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Alignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_Alignement");

                    b.ToTable("Alignments");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Achievement")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdAlignment")
                        .HasColumnType("int");

                    b.Property<int>("IdDirection")
                        .HasColumnType("int");

                    b.Property<int?>("IdGuild")
                        .HasColumnType("int");

                    b.Property<int?>("IdMainSpecializationClass")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("IdRace")
                        .HasColumnType("int");

                    b.Property<int?>("IdSecondarySpecializationClass")
                        .HasColumnType("int");

                    b.Property<int>("IdServer")
                        .HasColumnType("int");

                    b.Property<int>("Ilvl")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<bool>("Main")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Sentence")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Character");

                    b.HasIndex("IdAlignment");

                    b.HasIndex("IdDirection");

                    b.HasIndex("IdGuild");

                    b.HasIndex("IdMainSpecializationClass");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdRace");

                    b.HasIndex("IdSecondarySpecializationClass");

                    b.HasIndex("IdServer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.CharacterJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdJob")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdCharacter");

                    b.HasIndex("IdJob");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("CharacterJob", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_Class");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_Direction");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DateHourBegin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateHourEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EventGuild")
                        .HasColumnType("bit");

                    b.Property<int?>("IdAlignments")
                        .HasColumnType("int");

                    b.Property<int?>("IdOrganizer")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MinimumLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("http://icon-icons.com/icons2/632/PNG/512/event-planner_icon-icons.com_58034.png");

                    b.Property<int>("Places")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id")
                        .HasName("PK_Event");

                    b.HasIndex("IdAlignments");

                    b.HasIndex("IdOrganizer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCharacters")
                        .HasColumnType("int");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int?>("IdStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id")
                        .HasName("PK_tb_wow_ge_event_participant");

                    b.HasIndex("IdCharacters");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdStatus");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("EventParticipants");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.EventParticipantStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("EventParticipantStatus", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GamePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdGuild")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<string>("MediaKind")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdGuild");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdStatus");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("GamePost", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GamePostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("GamePostStatus", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdLeader")
                        .HasColumnType("int");

                    b.Property<int>("IdMainDirection")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LinkDiscord")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LinkForum")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Sentence")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdLeader");

                    b.HasIndex("IdMainDirection");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex(new[] { "Entitled", "Discriminator" }, "UQ_Guild_Handle")
                        .IsUnique();

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("IdGuild")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdGuild");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("GuildLinks");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdGuild")
                        .HasColumnType("int");

                    b.Property<int>("IdGuildRank")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id")
                        .HasName("PK_GuildMember");

                    b.HasIndex("IdCharacter");

                    b.HasIndex("IdGuildRank");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex(new[] { "IdGuild", "IdCharacter" }, "UQ_GuildMember_Character")
                        .IsUnique();

                    b.ToTable("GuildMember", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdGuild")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdCharacter");

                    b.HasIndex("IdGuild");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("GuildMessages");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("GuildRank", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildRequest", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdGuild")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdGuild");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("GuildRequest", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildVip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activation")
                        .HasColumnType("bit");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IdGuild")
                        .HasColumnType("int");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdGuild");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("GuildVip", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.LfgAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdDirection")
                        .HasColumnType("int");

                    b.Property<int?>("IdGuild")
                        .HasColumnType("int");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int?>("IdServer")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdDirection");

                    b.HasIndex("IdGuild");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("IdServer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("LfgAd", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlatformUserSnapshot", b =>
                {
                    b.Property<Guid>("PlatformUserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PlatformUserPublicId");

                    b.ToTable("PlatformUserSnapshot", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("IdKeycloak")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("IdRank")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NbMount")
                        .HasColumnType("int");

                    b.Property<Guid?>("PlatformUserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PresentationIg")
                        .HasColumnType("text");

                    b.Property<string>("PresentationIrl")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("SuccessPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("IdKeycloak")
                        .IsUnique()
                        .HasFilter("[IdKeycloak] IS NOT NULL");

                    b.HasIndex("PlatformUserPublicId")
                        .IsUnique()
                        .HasFilter("[PlatformUserPublicId] IS NOT NULL");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Icon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerLinks");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Share")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerPictures");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<int>("IdRank")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerRank", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Share")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerStream", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Share")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerVideos");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerVip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activation")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IdPlayer")
                        .HasColumnType("int");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdPlayer");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("PlayerVip", (string)null);
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.RaceClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<int>("IdRace")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdClass");

                    b.HasIndex("IdRace");

                    b.ToTable("RaceClasses");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Roster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdDirection")
                        .HasColumnType("int");

                    b.Property<int>("IdGuild")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdDirection");

                    b.HasIndex("IdGuild");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.RosterMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCharacter")
                        .HasColumnType("int");

                    b.Property<int>("IdRoster")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.HasKey("Id");

                    b.HasIndex("IdCharacter");

                    b.HasIndex("IdRoster");

                    b.HasIndex("IdSpecialization");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("RosterMembers");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdLocale")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.SpecializationClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<int>("IdSpecialization")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdClass");

                    b.HasIndex("IdSpecialization");

                    b.ToTable("SpecializationClasses");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Character", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Alignment", "IdAlignmentNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdAlignment")
                        .HasConstraintName("FK_Character_Alignment");

                    b.HasOne("WorldOfWarcraft.Database.Models.Direction", "IdDirectionNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdDirection")
                        .IsRequired()
                        .HasConstraintName("FK_Character_Direction");

                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdGuild")
                        .HasConstraintName("FK_Character_Guild");

                    b.HasOne("WorldOfWarcraft.Database.Models.SpecializationClass", "IdMainSpecializationClassNavigation")
                        .WithMany("CharacterIdMainSpecializationClassNavigations")
                        .HasForeignKey("IdMainSpecializationClass")
                        .HasConstraintName("FK_Character_SpecializationClass1");

                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_Character_Player");

                    b.HasOne("WorldOfWarcraft.Database.Models.Race", "IdRaceNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdRace")
                        .IsRequired()
                        .HasConstraintName("FK_Character_Race");

                    b.HasOne("WorldOfWarcraft.Database.Models.SpecializationClass", "IdSecondarySpecializationClassNavigation")
                        .WithMany("CharacterIdSecondarySpecializationClassNavigations")
                        .HasForeignKey("IdSecondarySpecializationClass")
                        .HasConstraintName("FK_Character_SpecializationClass2");

                    b.HasOne("WorldOfWarcraft.Database.Models.Server", "IdServerNavigation")
                        .WithMany("Characters")
                        .HasForeignKey("IdServer")
                        .IsRequired()
                        .HasConstraintName("FK_Character_Server");

                    b.Navigation("IdAlignmentNavigation");

                    b.Navigation("IdDirectionNavigation");

                    b.Navigation("IdGuildNavigation");

                    b.Navigation("IdMainSpecializationClassNavigation");

                    b.Navigation("IdPlayerNavigation");

                    b.Navigation("IdRaceNavigation");

                    b.Navigation("IdSecondarySpecializationClassNavigation");

                    b.Navigation("IdServerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.CharacterJob", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Character", "IdCharacterNavigation")
                        .WithMany("CharacterJobs")
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_CharacterJob_Character");

                    b.HasOne("WorldOfWarcraft.Database.Models.Job", "IdJobNavigation")
                        .WithMany("CharacterJobs")
                        .HasForeignKey("IdJob")
                        .IsRequired()
                        .HasConstraintName("FK_CharacterJob_Job");

                    b.Navigation("IdCharacterNavigation");

                    b.Navigation("IdJobNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Event", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Alignment", "IdAlignmentsNavigation")
                        .WithMany("Events")
                        .HasForeignKey("IdAlignments")
                        .HasConstraintName("FK_Event_Alignment");

                    b.HasOne("WorldOfWarcraft.Database.Models.Character", "IdOrganizerNavigation")
                        .WithMany("Events")
                        .HasForeignKey("IdOrganizer")
                        .HasConstraintName("FK_Event_Character");

                    b.Navigation("IdAlignmentsNavigation");

                    b.Navigation("IdOrganizerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.EventParticipant", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Character", "IdCharactersNavigation")
                        .WithMany("EventParticipants")
                        .HasForeignKey("IdCharacters")
                        .IsRequired()
                        .HasConstraintName("FK_tb_wow_ge_event_participant_tb_wow_ge_personnage");

                    b.HasOne("WorldOfWarcraft.Database.Models.Event", "IdEventNavigation")
                        .WithMany("EventParticipants")
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_tb_wow_ge_event_participant_tb_wow_ge_event");

                    b.HasOne("WorldOfWarcraft.Database.Models.EventParticipantStatus", "IdStatusNavigation")
                        .WithMany("EventParticipants")
                        .HasForeignKey("IdStatus")
                        .HasConstraintName("FK_EventParticipant_Status");

                    b.Navigation("IdCharactersNavigation");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdStatusNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GamePost", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("GamePosts")
                        .HasForeignKey("IdGuild")
                        .HasConstraintName("FK_GamePost_Guild");

                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("GamePosts")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_GamePost_Player");

                    b.HasOne("WorldOfWarcraft.Database.Models.GamePostStatus", "IdStatusNavigation")
                        .WithMany("GamePosts")
                        .HasForeignKey("IdStatus")
                        .IsRequired()
                        .HasConstraintName("FK_GamePost_Status");

                    b.Navigation("IdGuildNavigation");

                    b.Navigation("IdPlayerNavigation");

                    b.Navigation("IdStatusNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Guild", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Character", "IdLeaderNavigation")
                        .WithMany("Guilds")
                        .HasForeignKey("IdLeader")
                        .IsRequired()
                        .HasConstraintName("FK_Guilds_Characters");

                    b.HasOne("WorldOfWarcraft.Database.Models.Direction", "IdMainDirectionNavigation")
                        .WithMany("Guilds")
                        .HasForeignKey("IdMainDirection")
                        .IsRequired()
                        .HasConstraintName("FK_Guilds_Directions");

                    b.Navigation("IdLeaderNavigation");

                    b.Navigation("IdMainDirectionNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildLink", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("GuildLinks")
                        .HasForeignKey("IdGuild")
                        .IsRequired()
                        .HasConstraintName("FK_GuildLinks_Guild");

                    b.Navigation("IdGuildNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildMember", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Character", "IdCharacterNavigation")
                        .WithMany("GuildMembers")
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_GuildMember_Character");

                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("GuildMembers")
                        .HasForeignKey("IdGuild")
                        .IsRequired()
                        .HasConstraintName("FK_GuildMember_Guild");

                    b.HasOne("WorldOfWarcraft.Database.Models.GuildRank", "IdGuildRankNavigation")
                        .WithMany("GuildMembers")
                        .HasForeignKey("IdGuildRank")
                        .IsRequired()
                        .HasConstraintName("FK_GuildMember_GuildRank");

                    b.Navigation("IdCharacterNavigation");

                    b.Navigation("IdGuildNavigation");

                    b.Navigation("IdGuildRankNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildMessage", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Character", "IdCharacterNavigation")
                        .WithMany("GuildMessages")
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_GuildMessages_Characters");

                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("GuildMessages")
                        .HasForeignKey("IdGuild")
                        .IsRequired()
                        .HasConstraintName("FK_GuildMessages_Guilds");

                    b.Navigation("IdCharacterNavigation");

                    b.Navigation("IdGuildNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildRequest", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("GuildRequests")
                        .HasForeignKey("IdGuild")
                        .IsRequired()
                        .HasConstraintName("FK_GuildRequest_Guilds");

                    b.Navigation("IdGuildNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildVip", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("GuildVips")
                        .HasForeignKey("IdGuild")
                        .IsRequired()
                        .HasConstraintName("FK_GuildVip_Guilds");

                    b.Navigation("IdGuildNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.LfgAd", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Direction", "IdDirectionNavigation")
                        .WithMany()
                        .HasForeignKey("IdDirection")
                        .HasConstraintName("FK_LfgAd_Direction");

                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("LfgAds")
                        .HasForeignKey("IdGuild")
                        .HasConstraintName("FK_LfgAd_Guild");

                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("LfgAds")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_LfgAd_Player");

                    b.HasOne("WorldOfWarcraft.Database.Models.Server", "IdServerNavigation")
                        .WithMany()
                        .HasForeignKey("IdServer")
                        .HasConstraintName("FK_LfgAd_Server");

                    b.Navigation("IdDirectionNavigation");

                    b.Navigation("IdGuildNavigation");

                    b.Navigation("IdPlayerNavigation");

                    b.Navigation("IdServerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerLink", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerLinks")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerLinks_Player");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerPicture", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerPictures")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerPictures_Player");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerRank", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerRanks")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerRank_Player");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerStream", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerStreams")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerStream_Player");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerVideo", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerVideos")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerVideos_Player");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.PlayerVip", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Player", "IdPlayerNavigation")
                        .WithMany("PlayerVips")
                        .HasForeignKey("IdPlayer")
                        .IsRequired()
                        .HasConstraintName("FK_PlayerVip_Player");

                    b.Navigation("IdPlayerNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.RaceClass", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Class", "IdClassNavigation")
                        .WithMany("RaceClasses")
                        .HasForeignKey("IdClass")
                        .IsRequired()
                        .HasConstraintName("FK_RaceClasses_Class");

                    b.HasOne("WorldOfWarcraft.Database.Models.Race", "IdRaceNavigation")
                        .WithMany("RaceClasses")
                        .HasForeignKey("IdRace")
                        .IsRequired()
                        .HasConstraintName("FK_RaceClasses_Race");

                    b.Navigation("IdClassNavigation");

                    b.Navigation("IdRaceNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Roster", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Direction", "IdDirectionNavigation")
                        .WithMany("Rosters")
                        .HasForeignKey("IdDirection")
                        .IsRequired()
                        .HasConstraintName("FK_Rosters_Direction");

                    b.HasOne("WorldOfWarcraft.Database.Models.Guild", "IdGuildNavigation")
                        .WithMany("Rosters")
                        .HasForeignKey("IdGuild")
                        .IsRequired()
                        .HasConstraintName("FK_Rosters_Guild");

                    b.Navigation("IdDirectionNavigation");

                    b.Navigation("IdGuildNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.RosterMember", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Character", "IdCharacterNavigation")
                        .WithMany("RosterMembers")
                        .HasForeignKey("IdCharacter")
                        .IsRequired()
                        .HasConstraintName("FK_RosterMembers_Character");

                    b.HasOne("WorldOfWarcraft.Database.Models.Roster", "IdRosterNavigation")
                        .WithMany("RosterMembers")
                        .HasForeignKey("IdRoster")
                        .IsRequired()
                        .HasConstraintName("FK_RosterMembers_Roster");

                    b.HasOne("WorldOfWarcraft.Database.Models.Specialization", "IdSpecializationNavigation")
                        .WithMany("RosterMembers")
                        .HasForeignKey("IdSpecialization")
                        .IsRequired()
                        .HasConstraintName("FK_RosterMembers_Specialization");

                    b.Navigation("IdCharacterNavigation");

                    b.Navigation("IdRosterNavigation");

                    b.Navigation("IdSpecializationNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.SpecializationClass", b =>
                {
                    b.HasOne("WorldOfWarcraft.Database.Models.Class", "IdClassNavigation")
                        .WithMany("SpecializationClasses")
                        .HasForeignKey("IdClass")
                        .IsRequired()
                        .HasConstraintName("FK_SpecializationClasses_Class");

                    b.HasOne("WorldOfWarcraft.Database.Models.Specialization", "IdSpecializationNavigation")
                        .WithMany("SpecializationClasses")
                        .HasForeignKey("IdSpecialization")
                        .IsRequired()
                        .HasConstraintName("FK_SpecializationClasses_Specialization");

                    b.Navigation("IdClassNavigation");

                    b.Navigation("IdSpecializationNavigation");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Alignment", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Character", b =>
                {
                    b.Navigation("CharacterJobs");

                    b.Navigation("EventParticipants");

                    b.Navigation("Events");

                    b.Navigation("GuildMembers");

                    b.Navigation("GuildMessages");

                    b.Navigation("Guilds");

                    b.Navigation("RosterMembers");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Class", b =>
                {
                    b.Navigation("RaceClasses");

                    b.Navigation("SpecializationClasses");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Direction", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Guilds");

                    b.Navigation("Rosters");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Event", b =>
                {
                    b.Navigation("EventParticipants");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.EventParticipantStatus", b =>
                {
                    b.Navigation("EventParticipants");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GamePostStatus", b =>
                {
                    b.Navigation("GamePosts");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Guild", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("GamePosts");

                    b.Navigation("GuildLinks");

                    b.Navigation("GuildMembers");

                    b.Navigation("GuildMessages");

                    b.Navigation("GuildRequests");

                    b.Navigation("GuildVips");

                    b.Navigation("LfgAds");

                    b.Navigation("Rosters");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.GuildRank", b =>
                {
                    b.Navigation("GuildMembers");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Job", b =>
                {
                    b.Navigation("CharacterJobs");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Player", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("GamePosts");

                    b.Navigation("LfgAds");

                    b.Navigation("PlayerLinks");

                    b.Navigation("PlayerPictures");

                    b.Navigation("PlayerRanks");

                    b.Navigation("PlayerStreams");

                    b.Navigation("PlayerVideos");

                    b.Navigation("PlayerVips");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Race", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("RaceClasses");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Roster", b =>
                {
                    b.Navigation("RosterMembers");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Server", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.Specialization", b =>
                {
                    b.Navigation("RosterMembers");

                    b.Navigation("SpecializationClasses");
                });

            modelBuilder.Entity("WorldOfWarcraft.Database.Models.SpecializationClass", b =>
                {
                    b.Navigation("CharacterIdMainSpecializationClassNavigations");

                    b.Navigation("CharacterIdSecondarySpecializationClassNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
